import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import '../../styles/admin_style/AuditReportPreview.css';
import Portalheader from '../../components/Portalheader';
import Portalfooter from '../../components/Portalfooter';
import { fetchReport, getReportTypeMeta } from '../../services/reportService';

const SUMMARY_LABELS = {
  totalAssets: 'Total Assets',
  sold: 'Sold',
  unsold: 'Unsold',
  donatedOrScrap: 'Donated / Scrap',
  totalRecovery: 'Total Recovery (R)',
  totalTenders: 'Total Tenders',
  activeTenders: 'Active Tenders',
  withBids: 'With Bids',
  totalOffers: 'Total Offers',
  uniqueListings: 'Unique Listings',
  totalOfferValue: 'Total Offer Value (R)',
  totalExpiredUnsold: 'Expired Unsold',
  avgDaysSinceExpiry: 'Avg Days Since Expiry',
  totalUsers: 'Total Users',
  activeUsers: 'Active Users',
  pendingUsers: 'Pending Users',
  staffUsers: 'Staff Users',
  bidderUsers: 'Bidder Users',
  closedTenders: 'Closed Tenders',
  totalRecommended: 'Total Recommended (R)',
  overallRecoveryRate: 'Overall Recovery Rate',
  totalEvents: 'Total Events',
  uniqueUsers: 'Unique Users',
};

const AuditReportPreview = () => {
  const [searchParams] = useSearchParams();
  const reportType = searchParams.get('type') || 'disposal-outcomes';
  const startDate = searchParams.get('startDate') || '';
  const endDate = searchParams.get('endDate') || '';

  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      setLoading(true);
      setError('');

      try {
        const data = await fetchReport(
          reportType,
          startDate || undefined,
          endDate || undefined
        );
        if (!cancelled) {
          setReport(data);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err.message || 'Unable to load report.');
          setReport(null);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };

    load();
    return () => {
      cancelled = true;
    };
  }, [reportType, startDate, endDate]);

  const handlePrint = () => {
    window.print();
  };

  const meta = getReportTypeMeta(reportType);
  const generatedAt = report?.generatedAt
    ? new Date(report.generatedAt).toLocaleString()
    : new Date().toLocaleString();

  const summaryEntries = report?.summary
    ? Object.entries(report.summary)
    : [];

  const columnCount = report?.columns?.length || 1;

  return (
    <div className="arp-page">
      <Portalheader />

      <div className="arp-content">
        {loading && <p className="arp-status">Loading report…</p>}
        {error && <p className="arp-error" role="alert">{error}</p>}

        {!loading && !error && report && (
          <div className="arp-document">
            <div className="arp-doc-header">
              <div className="arp-doc-header-left">
                <div className="arp-doc-icon">📄</div>
                <div>
                  <span className="arp-doc-eyebrow">OFFICIAL DOCUMENT</span>
                  <h1 className="arp-doc-title">{report.title || meta?.title}</h1>
                </div>
              </div>
              <div className="arp-doc-header-right">
                <span className="arp-finalized-badge">✓ Generated</span>
                <span className="arp-meta-line"><strong>Date:</strong> {generatedAt}</span>
                <span className="arp-meta-line"><strong>Generated by:</strong> {report.generatedBy}</span>
                {(startDate || endDate) && (
                  <span className="arp-meta-line">
                    <strong>Period:</strong> {startDate || '…'} — {endDate || '…'}
                  </span>
                )}
              </div>
            </div>

            <hr className="arp-divider" />

            {summaryEntries.length > 0 && (
              <section className="arp-section">
                <span className="arp-section-heading">▤ Executive Summary</span>
                <div className="arp-stats-row">
                  {summaryEntries.map(([key, value]) => (
                    <div className="arp-stat-card" key={key}>
                      <div className="arp-stat-top">
                        <span className="arp-stat-label">{SUMMARY_LABELS[key] || key}</span>
                      </div>
                      <span className="arp-stat-value">{value}</span>
                    </div>
                  ))}
                </div>
              </section>
            )}

            <section className="arp-section">
              <span className="arp-section-heading">▥ Detail</span>

              <div
                className="arp-table-head arp-dynamic-table"
                style={{ gridTemplateColumns: `repeat(${columnCount}, minmax(0, 1fr))` }}
              >
                {report.columns.map((col) => (
                  <span key={col.key}>{col.label}</span>
                ))}
              </div>

              {report.rows.length === 0 ? (
                <p className="arp-empty-rows">No records match the selected criteria.</p>
              ) : (
                report.rows.map((row, index) => (
                  <div
                    className="arp-table-row arp-dynamic-table"
                    key={`row-${index}`}
                    style={{ gridTemplateColumns: `repeat(${columnCount}, minmax(0, 1fr))` }}
                  >
                    {report.columns.map((col) => (
                      <span key={col.key}>{row[col.key] ?? ''}</span>
                    ))}
                  </div>
                ))
              )}
            </section>

            <div className="arp-footer arp-no-print">
              <span className="arp-footer-note">Nelson Mandela University Asset Tender Portal</span>
              <div className="arp-footer-actions">
                <button type="button" className="arp-print-btn" aria-label="Print" onClick={handlePrint}>
                  🖶
                </button>
                <button type="button" className="arp-download-btn" onClick={handlePrint}>
                  ⭳ Download PDF
                </button>
              </div>
            </div>
          </div>
        )}
      </div>

      <Portalfooter />
    </div>
  );
};

export default AuditReportPreview;
