import React from 'react';
import AdminLayout from './AdminLayout';
import "../../styles/admin_style/AuditReportPreview.css";

const TRANSACTIONS = [
  { id: 1, lotId: 'L-8902', category: 'IT Equipment', buyer: 'TechRecycle Corp', value: '45,200.00', status: 'Cleared' },
  { id: 2, lotId: 'L-8903', category: 'Lab Instruments', buyer: 'BioMed Solutions', value: '112,050.00', status: 'Cleared' },
  { id: 3, lotId: 'L-8904', category: 'Office Furniture', buyer: 'Estate Liquidators', value: '18,500.00', status: 'Cleared' },
  { id: 4, lotId: 'L-8905', category: 'Fleet Vehicles', buyer: 'AutoAuctions Inc', value: '306,750.00', status: 'Cleared' },
];

const AuditReportPreview = () => {
  return (
    <AdminLayout pageLabel="Sample Audit Report Preview">
      <div className="arp-document">
        <div className="arp-doc-header">
          <div className="arp-doc-header-left">
            <div className="arp-doc-icon">📄</div>
            <div>
              <span className="arp-doc-eyebrow">OFFICIAL DOCUMENT</span>
              <h1 className="arp-doc-title">Institutional Asset Disposal Audit - Q4 2024</h1>
            </div>
          </div>
          <div className="arp-doc-header-right">
            <span className="arp-finalized-badge">✓ Finalized</span>
            <span className="arp-meta-line"><strong>Date:</strong> Dec 15, 2024</span>
            <span className="arp-meta-line"><strong>Ref ID:</strong> ADT-2024-Q4-892</span>
          </div>
        </div>

        <hr className="arp-divider" />

        <section className="arp-section">
          <span className="arp-section-heading">▤ Executive Summary</span>

          <div className="arp-stats-row">
            <div className="arp-stat-card">
              <div className="arp-stat-top">
                <span className="arp-stat-label">Total Assets Sold</span>
                <span className="arp-stat-icon">▦</span>
              </div>
              <span className="arp-stat-value">1,248</span>
              <span className="arp-stat-note arp-stat-note-positive">↑ +12% from Q3</span>
            </div>

            <div className="arp-stat-card arp-stat-card-highlight">
              <div className="arp-stat-top">
                <span className="arp-stat-label">Recovery Value</span>
                <span className="arp-stat-icon">📷</span>
              </div>
              <span className="arp-stat-value">$482,500</span>
              <span className="arp-stat-note arp-stat-note-positive">↗ Exceeds target</span>
            </div>

            <div className="arp-stat-card">
              <div className="arp-stat-top">
                <span className="arp-stat-label">Audit Compliance</span>
                <span className="arp-stat-icon">▤</span>
              </div>
              <span className="arp-stat-value">98.5%</span>
              <span className="arp-stat-note">◷ Status: Excellent</span>
            </div>
          </div>
        </section>

        <section className="arp-section">
          <span className="arp-section-heading">▥ Transaction Breakdown</span>

          <div className="arp-table-head">
            <span>Lot ID</span>
            <span>Category</span>
            <span>Buyer</span>
            <span className="arp-table-head-value">Value ($)</span>
            <span className="arp-table-head-status">Status</span>
          </div>

          {TRANSACTIONS.map((tx) => (
            <div className="arp-table-row" key={tx.id}>
              <span className="arp-lot-id">{tx.lotId}</span>
              <span className="arp-category">{tx.category}</span>
              <span className="arp-buyer">{tx.buyer}</span>
              <span className="arp-value">{tx.value}</span>
              <span className="arp-status-badge">{tx.status}</span>
            </div>
          ))}
        </section>

        <div className="arp-footer">
          <span className="arp-footer-note">Generated by UniAsset Automated Audit System</span>
          <div className="arp-footer-actions">
            <button type="button" className="arp-print-btn" aria-label="Print">🖶</button>
            <button type="button" className="arp-download-btn">⭳ Download PDF</button>
          </div>
        </div>
      </div>
    </AdminLayout>
  );
};

export default AuditReportPreview;